# Generated by Codex on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_transaction_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_holder',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
